/** @format */

/**
 * @fileoverview Custom middleware utility to handle and process validation errors generated by express-validator.
 * It consolidates all validation errors into a single string and throws a BadRequestError.
 *
 * @module ValidationResultUtils
 * @requires express-validator
 * @requires BadRequestError
 */
import { validationResult as expressValidationResult } from 'express-validator'
import { BadRequestError } from '../errors/customErrors.error.js'

/**
 * Creates and returns the final middleware function responsible for checking validation results.
 * If errors are present, they are compiled and thrown as a BadRequestError.
 *
 * @returns {Function} Express middleware function (req, res, next).
 */
function validationResult() {
	return (req, res, next) => {
		// Collect validation errors from the request
		const errors = expressValidationResult(req)

		if (!errors.isEmpty()) {
			// Map the error objects to just their messages (which come from i18n in middleware chains)
			const errorMessages = errors.array().map((error) => error.msg)

			// Concatenate all messages into a single string separated by '; '
			// and throw a custom 400 Bad Request error.
			throw new BadRequestError(errorMessages.join('; '))
		}
		// If no errors, proceed to the next middleware or controller function
		next()
	}
}

export { validationResult }
